FROM golang:1.24

# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    python3-pip \
    ffmpeg \
    && pip3 install yt-dlp --break-system-packages \
    && apt-get clean

WORKDIR /

COPY . .

RUN go build -o main main.go

EXPOSE 8080

CMD ["./main"]