FROM golang:1.24-bookworm AS build

WORKDIR /

COPY . .

RUN go build -o main .

FROM python:3.11-bookworm

RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    pip install yt-dlp && \
    apt-get clean

WORKDIR /
COPY --from=build /main .
COPY cookies.txt .

EXPOSE 8080

CMD ["./main"]