FROM golang:1.21

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    python3-pip \
    ffmpeg \
    && pip3 install yt-dlp --break-system-packages \
    && apt-get clean

WORKDIR /app

COPY . .

RUN go build -o app .

EXPOSE 8080

CMD ["./app"]