[build]
builder = "nixpacks"
buildCommand = "go build -o main ."

[deploy]
startCommand = "./main"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[packages]
apt = ["yt-dlp", "ffmpeg"]